### ISSUE TITLE
Minor UI issues

### ISSUE THREAD

**Issue by daar** [musa11971/filament-translation-manager#10]
The "quick translate" page shows some minor inconsistencies. The vertical alignment is not uniform for elements, as well one might want to use a card to align all elements.

![image](https://user-images.githubusercontent.com/865062/236880549-2404d6a6-8596-4d47-8251-bcd04963de86.png)

**Comment by musa11971** [comment]
Strange, this seems fine on my end. Looks like you may be missing some tailwind classes? (like my-4). 

<img width="790" alt="Screenshot 2023-05-09 at 10 31 13" src="https://user-images.githubusercontent.com/21341801/237040476-d846ca9d-ac58-4706-8344-b9910b97e040.png">

<img width="808" alt="Screenshot 2023-05-09 at 10 32 01" src="https://user-images.githubusercontent.com/21341801/237040490-a275fe37-ac25-4d83-8a8d-4170f588b68e.png">

**Comment by musa11971** [comment]
This repository will be moved to https://github.com/kenepa/translation-manager. Please feel free to re-open the issue there if it is relevant.
