### ISSUE TITLE
foreach() argument must be of type array|object, string given

### ISSUE THREAD

**Issue by mansoorkhan96** [musa11971/filament-translation-manager#2]
When i add `lang/en.json` file, i get following error:

```
foreach() argument must be of type array|object, string given
```

**Comment by Terefai** [comment]
any update?

**Comment by musa11971** [comment]
This package currently only supports the following translation set up (example):
```
lang
->	en
		->	users.php
		->	models.php
		->	views
				->	home.php
```

```php
// users.php example
return [
	'username' => 'Username',
	'add-friend' => 'Add this user as a friend'
];
```

**Comment by Solunsky** [comment]
I have this problem:
![image](https://user-images.githubusercontent.com/17966740/231898491-371395b7-33ba-45b3-b830-1e7afd97107b.png)

Structure in your example nice, but i get error

**Comment by musa11971** [comment]
@Solunsky what is the error? Please provide more details

**Comment by Solunsky** [comment]
> 

If i click button Synchronize, get message:

**Comment by dendevs** [comment]
Hello, great package!
I have the same small error.
I installed filament and exported the translation files.
Filament-support uses a structure with nested arrays and empty rows in its translation files.
This seems to create the error.
Couldn't we simply ignore the files which do not respect the structure usable by the package?
For the moment I have added in /vendor/musa11971/filament-translation-manager/src/Helpers/TranslationScanner.php line 51 an if( is_array($array) ) before the foreach.
It doesn't really solve the problem but it allows me to use the package :)

**Comment by Solunsky** [comment]
[lang.zip](https://github.com/musa11971/filament-translation-manager/files/11236421/lang.zip)

Didn't have time to see what the situation was, but I already thought to also make a fix in vendor.
Maybe you will quickly understand what the situation is.
Windows 11. PHP 8.1

**Comment by dendevs** [comment]
Yes of course. 
Here are the lang files directory and some screenshots, hope it helps.

[lang.zip](https://github.com/musa11971/filament-translation-manager/files/11238986/lang.zip)

![2023-04-14_10-01](https://user-images.githubusercontent.com/15471386/232205727-16e739ce-5769-440d-897f-ab17c7c673f2.png)

![2023-04-14_10-00](https://user-images.githubusercontent.com/15471386/232205732-45fa2983-e491-4548-b357-b25780135f8a.png)

![2023-04-14_09-59](https://user-images.githubusercontent.com/15471386/232205752-2e12033b-be06-4138-8760-53750be7d634.png)

**Comment by Solunsky** [comment]
My solution.
File: TranslationScanner.php
Method: Start()

```
$name = explode('/', $name);
unset($name[0]);
$name = implode('/', $name);
```

Replace to:
```
// Remove the first part (e.g. nl)
$name = explode('\\', $name);
unset($name[0]);
$name = implode('\\', $name);
```
`$this->traverseArray(trans($name, [], config('app.fallback_locale')), $seenCombinations, $allGroupsAndKeys, $name);`

Replace to:

`$this->traverseArray((array)trans($name, [], config('app.fallback_locale')), $seenCombinations, $allGroupsAndKeys, $name);`

**Comment by musa11971** [comment]
Thank you for the information, I have pushed and tagged a fix that should prevent this from happening. 

Unfortunately I found out vendor translations are currently not supported, so if anyone feels like it, feel free to create a PR for support.
