### ISSUE TITLE
navigation_group

### ISSUE THREAD

**Issue by Guil182bx** [musa11971/filament-translation-manager#5]
Hi,

After installation, navigation group doesn't appear but language switcher work.

Regards

**Comment by musa11971** [comment]
Hi @Guil182bx, did you setup the authorization gate?

https://github.com/musa11971/filament-translation-manager#authorization

**Comment by musa11971** [comment]
I noticed you did not change the gate, is the logic exactly the same in your application? If you do not need to do authorization logic, you can just return true in the gate. 

If that does not solve your issue, please provide more context

**Comment by Guil182bx** [comment]
Hi, that's it.
I modify like it : 
 Gate::define('use-translation-manager', function () {
            // Your authorization logic
            return optional(Auth::user())->is_admin === 1 && Auth::user()->hasAnyRole(['super-admin','admin','moderator']);
        });

But now, a have translation-manager page with "no records found".
when i click on "quick translate", i have "Nothing left to translate!"
when i click on "synchronize", i have an error : 

foreach() argument must be of type array|object, string given
\musa11971\filament-translation-manager\src\Helpers\TranslationScanner.php : 51

thanks for your help

**Comment by musa11971** [comment]
Hi, the error you shared is fixed in the latest package version. Please update and try again.

I’ll close this issue for now as it has been fixed
