### ISSUE TITLE
Synchronized 0 translations!

### ISSUE THREAD

**Issue by Guil182bx** [musa11971/filament-translation-manager#6]
Hi,

When i click on synchronize, i have : Synchronized 0 translations! and the table have "no records found" :/

regards

**Comment by musa11971** [comment]
Hi, please provide your lang folder

**Comment by Guil182bx** [comment]
Yes,
![lang](https://user-images.githubusercontent.com/95433254/233005431-42277b5f-bce8-4677-88f7-f0c5a8684f6e.jpg)

Regards

**Comment by musa11971** [comment]
Can you upload the lang folder as a zip file? Thanks

**Comment by Guil182bx** [comment]
[lang.zip](https://github.com/musa11971/filament-translation-manager/files/11271315/lang.zip)

regards

**Comment by musa11971** [comment]
Unfortunately vendor translations are currently not support by the package, which is why your translation keys are not showing up after synchronizing.

PR's are welcomed if you are able to deliver this functionality!
