### ISSUE TITLE
Operator does not exist: json = unknown

### ISSUE THREAD

**Issue by daar** [musa11971/filament-translation-manager#7]
Hi after installing this plugin. I get the following error when synchronizing my translations. I am using Postgresql as database

![image](https://user-images.githubusercontent.com/865062/236696600-46bfe9b5-5e78-4ad8-9359-2766ab525dea.png)

**Comment by musa11971** [comment]
Hi, unfortunately only mysql is supported at this moment, this is due to the query operator that is used to parse json fields.
